### ISSUE TITLE
pip doesn't install `psutil` dependency automatically

### ISSUE THREAD

**Issue by cdeil** [astrofrog/psrecord#14]
For me `pip install psrecord` did not install the `psutil` dependency automatically.

I think you have to put `install_requires` instead of `requires` in `setup.py` these days?
(and make a new release on PyPI so that this works).

**Comment by souravsingh** [comment]
Is the issue still open right now? If so,I would like to work on it

**Comment by astrofrog** [comment]
@souravsingh - yes, it's a simple fix, ``requires`` just needs to be changed to ``install_requires`` in ``setup.py`` - feel free to open a PR!
