### ISSUE TITLE
Fix compatibility with latest psutil version

### ISSUE THREAD

**Issue by astrofrog** [astrofrog/psrecord#15]
`get_cpu_percent` is now `cpu_percent`

**Comment by joezuntz** [comment]
Just a reminder about this issue which just hit me and looks like it shouldn't be too bad to fix!

**Comment by saimn** [comment]
@astrofrog  - I fixed that on my local copy last week, to be able to use psutil, but I forgot to open a PR ! I can push that later today.

**Comment by astrofrog** [comment]
It seems to work for me with the latest dev version, and was going to do another release now.

@saimn - what kind of changes did you have to make?

**Comment by saimn** [comment]
@astrofrog  - https://github.com/saimn/psrecord/commit/b6d2720992c8edc5897d969a112552bae65b2333
I pushed very quickly as I have to go. I had to use `children` instead of `get_children` and changes to get cpu/mem from subprocesses.

**Comment by astrofrog** [comment]
Thanks!

**Comment by astrofrog** [comment]
@saimn - thanks, I've included your fixes in https://github.com/astrofrog/psrecord/pull/19, and added some tests for better coverage.

**Comment by astrofrog** [comment]
@joezuntz - the latest developer version should now work correctly (thanks to @saimn's fix). Can you confirm that this is the case? I'm planning on doing a release once the Travis OSX builds work again and I'm able to confirm that this all works fine from a CI point of view.

**Comment by saimn** [comment]
@astrofrog - thanks !

**Comment by joezuntz** [comment]
Yep, works for me now - thanks!

**Comment by astrofrog** [comment]
@joezuntz - thanks for confirming! psrecord 1.0 is now out, so closing this.
