### ISSUE TITLE
--include-children It seems not working with % CPU usage

### ISSUE THREAD

**Issue by rubenmulero** [astrofrog/psrecord#27]
Hello.

I'm trying to monitor a Parent process that uses 21 child processes and I can't obtain the % CPU usage. The library returns me the % MEM usage but it doesn't returns the %CPU usage.

I tested using a UWSGI instance with 21 processes. All processes increase the CPU usage to 100%, but,  for some reason the library is not including the CPU usage of child processes. 

I used the command:

psrecord $1 --log results_${2}_seconds_.txt --include-children --duration $2

Where $1 is the PID and $2 is the duration of the test.

# Elapsed time   CPU (%)     Real (MB)   Virtual (MB)
       0.000        0.000     1695.492     9395.965
       0.278        0.000     1695.492     9395.965

I'm doing something wrong?

**Comment by rubenmulero** [comment]
Hello.

As far as I can see the problem is related with psutil library. I have made some tests and the problem seems to be in psutil. So this can be closed.

Regards.

**Comment by Dune-jr** [comment]
@rubenmulero  https://github.com/astrofrog/psrecord/pull/56 fixed it for me
