### ISSUE TITLE
Plot doesn't show up

### ISSUE THREAD

**Issue by ghostSystem** [astrofrog/psrecord#33]
On running the following command:
psrecord 1330 --log activity.txt --plot plot.png

After we use ctrl+z to stop the process the activity.txt file is created but there is no **plot.png** file created.

Moreover, I don't want to use --duration here.

How can this be solved ?

**Comment by ghostSystem** [comment]
Update. Should have used **ctrl+c** to stop the process. Now it shows up.

**Comment by astrofrog** [comment]
The reason ctrl+z didn't work is that it stops but does not terminate the process (that is, the process can be resumed or sent to the background).

**Comment by entenbein** [comment]
Did anyone try to stop psrecord from inside a bash script? Sending `SIGINT` after recording leaves me with just a log file and no pliot file.
