### ISSUE TITLE
Child processes CPU not monitored correctly

### ISSUE THREAD

**Issue by sandervrijders** [astrofrog/psrecord#47]
In every loop the process is queried for its children (all_children) upon which the CPU percentage is queried (get_percent). The first time get_percent is called 0 is returned however, since it uses the last measurement for a difference. Since every loop the list of children is reinitialized, only 0 is reported. So a list of child processes should be kept instead and checked if new child processes were created or if some have died. Better yet the loop can be simplified to run through the list of all processes to be monitored (if --include-children is not set than the set only contains the main process, otherwise the main process and its children) and on every process the CPU and mem usage is queried.

**Comment by conz27** [comment]
Fixed in Pull Request #56

**Comment by astrofrog** [comment]
This should now be fixed in psrecord v1.2 - please re-open if not!
