### ISSUE TITLE
0% CPU utilization

### ISSUE THREAD

**Issue by humbletroll** [astrofrog/psrecord#57]
Hi. So I am using psrecord to plot graph for cpu utilization and memory for linux sort. I did use --include-children but it shows 0% CPU utilization. I had started the process via the psrecord directly. While it says the issue is fixed, it doesn't look like so.

**Comment by Feromrk** [comment]
I am also facing the same issue over here.

**Comment by Feromrk** [comment]
Just switch to https://github.com/astrofrog/psrecord/pull/56, which fixes this issue.

**Comment by astrofrog** [comment]
I think this should now be fixed in psrecord v1.2 - could you confirm and close this if so?
